### ISSUE TITLE
Update Release Plan

### ISSUE THREAD

**Issue by bbest31** [CMPUT301W17T22/MoodSwing#15]
Plan the major use cases and user stories that need to be done for project part 5. This plan will likely evolve and should be maintained up-to-date in your team wiki. It should be clear from the plan the progress towards satisfying all the specified requirements.

Comment any suggestions for Fred to do here on this Issue.

**Comment by bbest31** [comment]
Based on TA feedback we need to include who is doing what use cases in our release plan, we will get that sorted out today at the meeting and then you can put it into our release plan.

**Comment by fdrury** [comment]
Completed
