### ISSUE TITLE
UML Changes for Part 3

### ISSUE THREAD

**Issue by bbest31** [CMPUT301W17T22/MoodSwing#25]
**These are changes need to be made to the current UML**

- [x] MoodSwing class needs these methods removed: addMoodEvent, deleteMoodEvent, editMoodEvent, editFollowingList, editFollowerList.

**Comment by peterweckend** [comment]
- [x]  **New FollowerList:**
public void createRequest(Participant requestingParticipant)
public void approveRequest(Participant requestingParticipant, Participant receivingParticipant)
public void declineRequest(Participant requestingParticipant, Participant receivingParticipant)
public boolean removeFollowRequest(Participant receivingParticipant)
_Getters/Setters (if needed)_
public ArrayList<Participant> getFollowers()
public ArrayList<Participant> getPending()

- [x]  **New FollowingList**
public void followParticipant(Participant receivingParticipant, Participant requestingParticipant)
public void followRequestApproved(Participant receivingParticipant)
public boolean followRequestDenied(Participant receivingParticipant)
_Getters/Setters (if needed)_
 public ArrayList<Participant> getPending()
public ArrayList<Participant> getFollowing()


- [x]  **New FollowerController (pretty sure this is what we need)**
public void createFollowerRequest(Participant requestingParticipant)
public void approveFollowerRequest(Participant requestingParticipant)
public void declineFollowerRequest(Participant requestingParticipant)

- [x]  **New FollowingController (pretty sure this is what we need)**
public void followParticipant(Participant receivingParticipant)
public void followRequestApproved(Participant receivingParticipant)
public void followRequestDeclined(Participant receivingParticipant)
