### ISSUE TITLE
Add location to mood event

### ISSUE THREAD

**Issue by fdrury** [CMPUT301W17T22/MoodSwing#36]
Get/save latitude and longitude when creating a mood event

- [x] get location
- [x] show map

**Comment by htruong4** [comment]
Some notes from the android site:
There are multiple ways to approach estimating location of the user/participant:
We will have to discuss what may be better.
1. GPS, cell ID, Wifi provide ideas of where the user may be.  Each have different trades off based on accuracy and battery draining.
2. Possibly need to account for user movement to update location (makes sense because of the 5 KM range)
3.Accuracy of current location varies  based on location source.

**Comment by fdrury** [comment]
I think there may be a way to ask the user if they want to enable GPS (most accurate but drains battery) and then when finding location, the app can go with the best available/allowed option (whether GPS, IP, etc.)?

**Comment by htruong4** [comment]
I believe I read something like that can work. I'm up to do that

**Comment by htruong4** [comment]
We need to also make a model for the update of location so we don't drain the battery too fast albeit I don't think it will be the biggest concern for this project but it could be a semi "wow" factor.

**Comment by htruong4** [comment]
I will link this as a reference for it contains some good stuff and information as I keep digging around.

https://developer.android.com/guide/topics/location/strategies.html

**Comment by fdrury** [comment]
There might even be open source code somewhere with a good strategy (or a strategy that we can modify to meet our needs)

**Comment by htruong4** [comment]
Oh that is most true. For now I'll keep digging around to see what we may need and I'll try something out on my desktop at home.

**Comment by htruong4** [comment]
Posting this link as a reference for myself tonight to try. 

https://developers.google.com/maps/documentation/android-api/start

**Comment by htruong4** [comment]
Maps with marker reference

https://developers.google.com/maps/documentation/android-api/map-with-marker

**Comment by htruong4** [comment]
map objects: https://developers.google.com/maps/documentation/android-api/map

**Comment by htruong4** [comment]
reference for map fragment to review:

http://stackoverflow.com/questions/35496493/getmapasync-in-fragment

**Comment by fdrury** [comment]
For tracking location:
https://developer.android.com/training/location/index.html
I will try to test this tomorrow night

**Comment by fdrury** [comment]
It would be nice to grey out the "include location" option if the location is returned as null (not known)

**Comment by fdrury** [comment]
It looks like the example Map activity is a fragment so we might be able to copy that code over to the feed. I will try tomorrow.

**Comment by htruong4** [comment]
I'm still trying to  figure out how to place everything since there is a lot of methods to use.

**Comment by fdrury** [comment]
promising code for getting location: https://examples.javacodegeeks.com/android/android-location-api-using-google-play-services-example/

**Comment by fdrury** [comment]
next to try:
http://blog.teamtreehouse.com/beginners-guide-location-android

**Comment by fdrury** [comment]
Nearing completion.
Awaiting integration to current build and linking to other features

**Comment by fdrury** [comment]
This part of loactions is done. New issues can be openned for other location related issue and taks
