### ISSUE TITLE
Intent testing

### ISSUE THREAD

**Issue by fdrury** [CMPUT301W17T22/MoodSwing#39]
- [x] login (redo)
- [x] add mood event (redo)
- [x] view mood history (redo)
- [x] view mood event (redo)
- [x] edit mood event (redo)
- [x] follower/following 
- [x] mood feed
- [x] mood feed filter
- [x] block list
- [ ] 
- [ ] 

- more to come...

**Comment by peterweckend** [comment]
is this the same as the intent testing?

**Comment by fdrury** [comment]
yes sir

**Comment by peterweckend** [comment]
modifications (todo):
- Add safe login (grab by intent instead of button)
- Add solo.sleep to more intensive actions
- When navigating in main menu bar, add clickOnActionBarItem and WaitFor(Home)

Need to account for tabs not updating, need to wait a few seconds for follower/following to be entered
