### ISSUE TITLE
Peter Unit Testing (4 cases)

### ISSUE THREAD

**Issue by bbest31** [CMPUT301W17T22/MoodSwing#4]
**Classes to Test for Peter**

- [x] - Emotional State
- [x] - Follower List
- [x] - Following List (following unit test)
- [x] - Mood Options

**Comment by bbest31** [comment]
Currently Working...

**Comment by peterweckend** [comment]
FollowingUnitTest tests both the follower list and the following list

**Comment by fdrury** [comment]
Splitting FollowingUnitTest into 2 files may be more clear

**Comment by peterweckend** [comment]
Done
> agreed, I'll try and do that
